"use strict";
// All gameplay tuning lives here. Art dimensions and sound envelopes stay with their renderers.
const BALANCE = {
  happiness: { start: 70, max: 100, anxious: 35, critical: 12, cueCooldown: 4 },
  food: [
    { name: "Сосиска", score: 1, happy: 5 },
    { name: "Печенье", score: 2, happy: 7 },
    { name: "Куриная ножка", score: 3, happy: 10 },
    { name: "Пончик", score: 2, happy: 8 },
    { name: "Брокколи", score: -5, happy: -10 },
    { name: "Морковь", score: -5, happy: -10 },
    { name: "Цветная капуста", score: -5, happy: -10 },
    { name: "Косточка", score: 0, happy: 0 },
    { name: "Кирпич", score: -5, happy: -12 },
  ],
  difficulty: {
    gain: 1 / 85,
    smoothing: 0.7,
    fallStart: [3.9, 4.4],
    fallEnd: [2.35, 2.75],
    spawnStart: [0.58, 0.7],
    spawnEnd: [0.3, 0.39],
    hazardStart: 0.13,
    hazardEnd: 0.29,
  },
  spawning: {
    first: 0.3,
    sausageChance: 0.75,
    boneChance: 0.06,
    brickChance: 0.12,
    maxItems: 14,
    eventMaxItems: 18,
    maxHazardRun: 2,
    attempts: 9,
    gapX: 62,
    gapY: 58,
    top: -28,
    brickWarning: 0.65,
    brickSpeedMultiplier: 1.4,
  },
  introduction: {
    otherFood: 3,
    hazards: 6,
    bones: 9,
    specials: 7.5,
    badSpecials: 11,
    bricks: 15,
  },
  specials: {
    goodChance: 0.38,
    badChance: 0.2,
    goodCooldown: 5.5,
    goodPity: 9,
    badCooldown: 4,
    badPool: ["freeze", "jam", "wind", "heavy", "wave"],
    goodPool: [
      "magnet",
      "shield",
      "double",
      "helpers",
      "helpers",
      "birds",
      "birds",
      "rain",
      "slow",
      "trail",
      "mouth",
      "swift",
      "chance",
    ],
  },
  durations: {
    rain: 4,
    slow: 4.5,
    trail: 4.5,
    mouth: 6,
    swift: 5.5,
    chance: 6,
    wind: 3.5,
    heavy: 2.5,
    wave: 3.5,
    magnet: 4,
    shield: 6,
    double: 5,
    helpers: 5,
    birds: 5,
    freeze: 1.1,
    stun: 2.3,
    jam: 3,
  },
  immunity: 1.8,
  bones: { maxMultiplier: 1.75, decay: 0.22 },
  helpers: {
    first: 0.25,
    catsInterval: 0.65,
    birdsInterval: (0.65 * 2) / 3,
    flight: 0.55,
    cutoff: 0.6,
  },
  magnet: { startHeight: 0.28, range: 0.48, pull: 7, belowCatch: 10 },
  event: {
    rainCount: 14,
    rainInterval: 0.25,
    trailChains: 3,
    chainLength: 4,
    chainInterval: 0.24,
    chainGap: 0.45,
    chainRequired: 3,
    chainReward: 3,
    minFall: 2.8,
    slowFactor: 0.58,
    mouthFactor: 1.23,
    swiftFactor: 1.28,
    heavyFactor: 0.75,
    windSpeed: 0.035,
    warning: 0.5,
    waveExtra: 0.11,
    bounceGravity: 0.9,
    bounceVelocity: 0.6,
    jackpotCue: 6,
  },
  doubleMultiplier: 2,
  combo: { thresholds: [5, 10, 20, 30], reward: 0 },
  nearMiss: { distance: 14, cueCooldown: 0.8, reward: 0 },
  rhythm: {
    first: 22,
    gap: 28,
    lateGap: 17,
    rest: 2.5,
    restSpawn: 1.3,
    restHazard: 0.6,
    duration: 5,
    rushSpawn: 0.85,
    rushHazard: 0.5,
    rushSausage: 0.95,
    waveSpawn: 0.94,
    waveHazard: 0.03,
  },
  collision: { halfWidth: 42, padding: 10, above: 17, below: 20 },
  missedSausagePenalty: 1,
  feedback: {
    life: 0.8,
    maxEffects: 18,
    vibration: 40,
    chew: 0.78,
    reaction: 0.5,
  },
  input: { keyboardSpeed: 1.2, follow: 26, maxFollow: 4.5 },
  frame: { maxDelta: 0.04, maxDpr: 1.5 },
};
function boneMultiplier(count) {
  return (
    1 +
    (BALANCE.bones.maxMultiplier - 1) *
      (1 - Math.exp(-BALANCE.bones.decay * Math.max(0, count)))
  );
}
function isHazard(type) {
  return (type >= 4 && type <= 6) || type === 8;
}
